tours:
  01355ebb-1272-4a5b-82b9-772b68305779:
    name_he: Off the track
    emoji: 🎨
    description_he: |-
      סיור בשכונת גרסיה האותנטית — קאסה וויסנס (הבית הראשון של גאודי), אמנות רחוב, סמטאות מלאות חנויות מעצבים, שוק האוכל של השכונה ומנה גדושה של תרבות קטלאנית.
    meeting_point_he: Fontana תחנת מטרו
    google_maps_url: https://maps.app.goo.gl/EVrC4YqCMDomz5X58
  080f3740-493b-4904-88e0-81fc1d9edc86:
    name_he: מוזיאון דאלי
    emoji: 🎨
    description_he: |-
      טיול יום למוזיאון דאלי בפיגרס — העולם הסוריאליסטי של אחד הציירים הגדולים של המאה ה-20.
      בואו לגלות את הסיפורים המרתקים מאחורי היצירות של האדם והשפם האייקוני.
    meeting_point_he: Hard Rock Cafe, Plaça de Catalunya, Barcelona, Spain
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  2938c20e-73bb-46c1-8230-241fd38180ed:
    name_he: סיור פלמנקו
    emoji: 🎸
    description_he: |-
      סיור מוזיקלי ייחודי עם עופר רונן, גיטריסט פלמנקו בינלאומי.
      נטייל בסמטאות שכונת בורן העתיקה, נשמע את סיפורי הפלמנקו ונהנה מנגינות חיות לאורך כל הסיור.
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  2a41c826-3038-4de7-b1bc-8c7783c36f65:
    name_he: הסיפור היהודי
    emoji: ✡️
    description_he: |-
      סיור על ההיסטוריה היהודית בספרד בכלל ובברצלונה בפרט.
      נבקר ברובע היהודי, בית הכנסת העתיק, כיכר המלך של ויכוח הרמב״ן, מצבות יהודיות, נשמע על תקופת תור הזהב, האינקוויזיציה, צו הגירוש ונכיר לעומק את תרומתה החשובה של הקהילה היהודית בספרד מאז ועד היום.
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  35558252-7493-4b31-87bb-869c03596d18:
    name_he: טיול יום לפירינאים
    emoji: 🏔️
    description_he: |-
      טיול יום משגע אל עמק נוריה ברכס הפירנאים הירוק בקיץ והמושלג בחורף — טבע, הרים ונופים עוצרי נשימה.
    meeting_point_he: Hard Rock Cafe, Plaça de Catalunya, Barcelona, Spain
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  4422ee5f-957b-45c8-bf06-876482fd2b57:
    name_he: גותיראמבלה ללא הפסקה
    emoji: 🌻
    description_he: |-
      סיור מרתק למנהרת הזמן של העיר ברצלונה- במהלך הסיור נלמד על ההיסטוריה, התרבות, המנהגים המסורת המקומית, אדריכלות משגעת, הקתדרלה היפהפה, הרובע היהודי, כיכר העיירה, המקדש הרומי, קיר הנשיקה ועוד! הכל תוך כדי שיטוט בסמטאות היפהפיות של הרובע הגותי.
    meeting_point_he: 10:15 בכניסה למסעדת הארד רוק קפה, פלאסה קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  45ad4093-4d64-45f0-b06b-7f4d5057151f:
    name_he: שוקולולה
    emoji: 🍫
    description_he: |-
      הדם שזורם לכם בגוף עשוי משוקולד?! סיור שוקולולה הוא בדיוק בשבילכם! סיור מתוק במיוחד בסמטאותיה של העיר העתיקה! במהלך הסיור נבקר בכל הקונדיטוריות והמאפיות הכי שוות במרכז העיר- עוגות, שוקולדים, מאפים וקינוחים מקומיים ייחודים- סיור שישאיר אותכם עם טעם של עוד!.
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  65eaee7a-986d-4dc3-a354-4d5c7a43ff40:
    name_he: פיקניק על הר המונטסראט
    emoji: ⛰️
    description_he: |-
      חצי יום טיול להר הקדוש ביותר בקטלוניה — נתחיל בנסיעה ברכבת, נמשיך ברכבל אל המנזר הבנדיקטי המרשים, נשמע על האגדה של המדונה השחורה, נטעם מאכלים מיוחדים בשוק האיכרים ונסיים בפיקניק של יין וגבינות מול הנוף המשגע של רכס הרי המונטסראט.
    meeting_point_he: Buenas Migas - ליד בית הקפה Plaça d'Espanya, 6
    google_maps_url: https://maps.app.goo.gl/SRCeTBbk5pr1cu1C7
  7a2e010f-69c3-4c63-8971-4f446826272a:
    name_he: English Barcelona Jewish Tour
    emoji: 🕎
    language: en
    description_he: |-
      The Jewish History of Barcelona — The Jewish quarter, the ancient synagogue, Plaça del Rei of the Ramban debate, Jewish tombstones, mezuzah markings and much more. Join us on a journey through Jewish heritage, from past to present.
    meeting_point_he: Hard Rock Cafe, Plaza Catalunya
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  83faaa08-7ce3-4cf5-8743-637f2b92371b:
    name_he: בארסהלולה
    emoji: ⚽
    description_he: |-
      סיור מרתק למוזיאון הכדורגל של בארסה והקאמפ נואו, נכיר את ההיסטוריה של המועדון המפורסם, נזכה לראות את כדורי ונעלי הזהב של מסי, הגביעים מכל הזמנים, רגעים מכוננים של המועדון ועוד ועוד!
    meeting_point_he: 10:00 בכניסה למסעדת הארד רוק קפה, פלאסה קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  8420a1dd-4002-46ef-86f2-5f0f719ec760:
    name_he: בין ים להר
    emoji: 🌊
    description_he: |-
      מסע אל נפלאות הטבע של ברצלונה — שער הניצחון, פארק סיוטדלה, המזרקה היפה ביותר בעיר, שכונת ברצלונטה, ולסיום- חופי הים והטיילת המשגעת.
    meeting_point_he: שער הנצחון
    google_maps_url: https://maps.app.goo.gl/j8vGsEXiCjKqfpth6
  85ed2080-ef9f-4b18-9c75-565910cc5326:
    name_he: סיור ילדים-חפש את הדרקון
    emoji: 🐉
    description_he: |-
      סיור חוויתי לכל המשפחה — סיור הילדים שלנו יפתח את הסקרנות והיצירתיות של הילדים, יעודד עבודת צוות עם שאר חברי הקבוצה, ויעשיר את הידע של ילדיכם על העיר ברצלונה והתרבות הקטלאנית.
    meeting_point_he: חנות Burberry ברחוב Passeig de gracia 56
    google_maps_url: https://maps.app.goo.gl/Eswmrtpo6VpvDzD27
  8d7c14c1-144d-4008-928c-59f2e966c096:
    name_he: טאפאס והעיר הגדולה
    emoji: 🍷
    description_he: |-
      להתאהב בברצלונה דרך הבטן — מסע קולינרי של 3.5 שעות עם שלל טאפאסים, פאייה אותנטית 4 משקאות אלכוהולים, ו-2 שכונות בעיר העתיקה.
      לאורך הסיור נבקר בברי טאפאסים מקומיים ונשמע שלל סיפורים על התרבות הקולינרית הספרדית והקטלאנית. מבטיחים לכם שתצאו עם בטן מלאה וחיוך מאוזן לאוזן
    meeting_point_he: מלון Suizo בסמוך למטרו Jaume 1 ברובע הגותי
    google_maps_url: https://maps.app.goo.gl/BkAHf15vtccYCgJK8
  a0cc2580-243a-4769-ae18-d251d5138834:
    name_he: טיול יום לקוסטה בראווה
    emoji: 🏖️
    description_he: |-
      טיול יום משגע אל פנינות הקוסטה בראווה — טוסה דה מאר עם המים הצלולים והמצודה העתיקה, ועיירת בלאנס עם אחד מהגנים הבוטנים היפים באירופה.
    meeting_point_he: Hard Rock Cafe, Plaça de Catalunya, Barcelona, Spain
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  a71b972a-c660-45fc-b8f7-dfda507ab5f4:
    name_he: הצד האפל של ברצלונה
    emoji: 🌙
    description_he: |-
      סיור לילי בסמטאות העיר העתיקה — בואו להכיר אתנו את כל הסודות האפלים והכמוסים של העיר- נדבר על האינקוויזיציה הספרדית, הערפדית של ברצלונה, כיכרות ההוצאה להורג, הברים האגדיים ועוד הפתאות.. כי ברצלונה של הלילה היא לא ברצלונה של היום.
      (מגיל 16 ומעלה.)
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  abccdd90-4eae-4b1b-8f37-401a69236973:
    name_he: היהודים באים
    emoji: 🏔️
    description_he: |-
      סיור פסטורלי להר היהודים היפהפה, הריאה הירוקה של העיר, ומשם נראה נוף עוצר נשימה על  ברצלונה ונטייל ברוגע בין הפארקים הפסטורלים, האתרים והמונומנטים היפים על ההר.
    meeting_point_he: 15:00 ליד תיאטרון Apolo, צמוד לתחנת המטרו Paral·lel
    google_maps_url: https://maps.app.goo.gl/yVfXg1haSD69Wbv78
  b029e88a-999c-4131-9d8e-13e36a53cff4:
    name_he: סיור כריסטמס
    emoji: 🎄
    description_he: |-
      סיור לילי בין האורות המנצנצים של ברצלונה והפתעות מתוקות וטעימות — במהלך הסיור נלמד על המנהגים המקומיים של חג המולד ונבקר ברובע הגותי, שוק הכריסטמס ושדרת פאסג׳ דה גרסיה המרהיבה.
      מסיימים עם מופע האורות על קאסה באטיו של גאודי.
    meeting_point_he: בית הקפה Starbucks בכיכר Jaume ברובע הגותי
    google_maps_url: https://maps.app.goo.gl/6WUKmYTw9gwUCyjp9
  cb3cabd9-a49b-49e9-a0dc-98b6b06bc91e:
    name_he: מתגלגלולה-סיור אופניים
    emoji: 🚴
    description_he: |-
      בואו לדווש ולהתרגש איתנו בסיור אופניים מעגלי העובר דרך גרפיטי בשכונת רבאל, הנמל הישן, פארק סיוטדלה, שער הנצחון, חוף ברצלונטה, הנמל האולימפי, הסגרדה פמיליה, קאסה מילה וקאסה באטיו.
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  d9807937-2c23-4f57-9eec-232ba2360f37:
    name_he: המסע בעקבות גאודי והמודרניסטה
    emoji: 🌻
    description_he: |-
      המסע בעקבות גאודי ואדריכלות המודרניסטה — בסיור נכיר ונלמד על הקטלאני המפורסם מכולם, ה״משוגאון״ של ברצלונה, האדריכל המוכשר- אנטוניו גאודי. במהלך הסיור נראה את המבנים היפהפיים שלו ואדריכלים חשובים בני תקופתו על שדרת פאסג׳ דה גרסיה- קאסה ליאו מוררה, קאסה אמטלייר, קאסה מילה וקאסה באטיו.
      מסיימים בכנסיה החשובה, מפעל חייו של גאודי וסמלה של העיר ברצלונה- הסגרדה פמיליה.
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  dc36e0c8-8ff7-423f-96d9-ed665f1c811b:
    name_he: Born to be Wild
    emoji: 🍤
    description_he: |-
      סיור קולינריה ואמנות בסמטאות אל בורן הבוהמיינית — טאפאסים משובחים, קונדיטוריית הופמן האגדית, כנסיית סנטה מריה דל מאר, מוזיאון פיקאסו, גרפיטי צבעוני, גלריות אמנות וחנויות מעצבים.
      מסיימים בארמון המוזיקה המרהיב. תגיעו רעבים!
    meeting_point_he: תחנת המטרו Jaume 1, בצמוד למלון Suizo ברובע הגותי
    google_maps_url: https://maps.app.goo.gl/BkAHf15vtccYCgJK8
  dd8af144-a2d1-437a-84b9-223b4c09ad8b:
    name_he: קרנבל באל רבאל
    emoji: 🎨
    description_he: |-
      סיור גרפיטי ואמנות רחוב צבעוני במיוחד בשכונה ההיפסטרית אל-רבאל — נדבר ונלמד על תרבות הגרפיטי העולמית ועל הסצנה של ברצלונה בפרט. נכיר יצירות של אמני גרפיטי מקומיים ובינלאומיים, החתול המפורסם של ברצלונה, המוזיאון לאמנות עכשווית, הגרפיטי של קית׳ הרינג, ונכיר מקרוב את הסיפור המרתק של שכונת רבאל!
    meeting_point_he: מסעדת הארד רוק קפה, כיכר קטלוניה
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
  e7433ad3-1883-4f57-8ff4-f1bd4e3ef0d4:
    name_he: טיול יום לג׳ירונה ובסלו
    emoji: 🕍
    description_he: |-
      טיול יום לשתי ערים מרתקות — ג׳ירונה ובסלו.
      טיול שכולו יהדות אל שתי ערים קטלאניות עתיקות עם היסטוריה יהודית עשירה ומרתקת. במהלך הסיור נכיר ונחשוף סודות ושרידים מתקופת תור הזהב של יהדות ספרד, נשמע סיפורים מרתקים על הרמב״ן ורבנים חשובים נוספים, מקוואות, בתי כנסת ומוזיאון יהודי יפהפה.
    meeting_point_he: Hard Rock Cafe, Plaça de Catalunya, Barcelona, Spain
    google_maps_url: https://maps.app.goo.gl/3nbsJJytm6HnDGXL8
